# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lzfavVdZE0xk0p_IkID2zWyTKMqC9xfz
"""

i = 1
while i<= 10:
  print(i)
  i+=1